package edu.gatech.cs2340.spacetrader.entity;

/**
 * the resources available on planets
 */
public enum Resources {
    MINERALRICH, MINERALPOOR, DESERT, LOTSOFWATER, RICHSOIL, POORSOIL, RICHFAUNA, LIFELESS,
    WEIRDMUSHROOMS, LOTSOFHERBS, ARTISTIC, WARLIKE, DROUGHT, WAR, COLD,
    CROPFAIL, BOREDOM, PLAGUE, LACKOFWORKERS

}
