package edu.gatech.cs2340.spacetrader.entity;

public enum Resources {
    MINERALRICH, MINERALPOOR, DESERT, LOTSOFWATER, RICHSOIL, POORSOIL, RICHFAUNA, LIFELESS,
    WEIRDMUSHROOMS, LOTSOFHERBS, ARTISTIC, WARLIKE, DROUGHT, WAR;
}
